--INIT ADMIN
INSERT INTO ADMIN(USERNAME, PASSWORD, ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, AUTHORITIES) VALUES('admin','$2a$10$i2Ayn28fzaWsFCWpSp9Av.qhwGTBQjGxN83uERxodVPSdtDiooUYa', true, true, true, true, 'USER,ADMIN');
